# Generated by Django 2.2 on 2019-04-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190403_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.PersonStatus'),
        ),
    ]
