# Generated by Django 2.2 on 2019-04-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190403_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Event'),
        ),
    ]
